name: ci

on:
  push:
    branches:
      - 'feature/docker'
      - 'master'
      - 'main'
      - 'fancy'
      - 'pants'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set env
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: c8n.io/lerring
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: c8n.io/lerring/shmea-db:${{ env.BRANCH }}
          build-args: |
            BRANCH=${{ env.BRANCH }}
